# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-29 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtimecore', '0002_fill_workhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='queue',
            field=models.CharField(default='general', max_length=25, verbose_name=b'Queue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=25, verbose_name=b'Username'),
        ),
    ]
